USE [AIR_CANADA]
GO

--Step 01 - Create connections
CREATE LOGIN LOGIN1
WITH PASSWORD = N'USER1',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN2
WITH PASSWORD = N'USER2',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN3
WITH PASSWORD = N'USER3',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN4
WITH PASSWORD = N'USER4',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN5
WITH PASSWORD = N'USER5',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN6
WITH PASSWORD = N'USER6',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN7
WITH PASSWORD = N'USER7',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN8
WITH PASSWORD = N'USER8',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO

CREATE LOGIN LOGIN9
WITH PASSWORD = N'USER9',
DEFAULT_DATABASE = [AIR_CANADA],
CHECK_EXPIRATION = OFF,
CHECK_POLICY = OFF
GO


--Step 02 - Associate connections to users.
USE [AIR_CANADA]
GO

CREATE USER [USER1] FOR LOGIN [LOGIN1]
GO

CREATE USER [USER2] FOR LOGIN [LOGIN2]
GO

CREATE USER [USER3] FOR LOGIN [LOGIN3]
GO

CREATE USER [USER4] FOR LOGIN [LOGIN4]
GO

CREATE USER [USER5] FOR LOGIN [LOGIN5]
GO

CREATE USER [USER6] FOR LOGIN [LOGIN6]
GO

CREATE USER [USER7] FOR LOGIN [LOGIN7]
GO

CREATE USER [USER8] FOR LOGIN [LOGIN8]
GO

CREATE USER [USER9] FOR LOGIN [LOGIN9]
GO


--Step 03 - Assign SysAdmin role to Login9.
ALTER SERVER ROLE [sysadmin]
ADD MEMBER [LOGIN9]
GO


--Step 04 - SELECT privileges
--Q04.1 - Cannot proceed. User1 doesn't have the privileges to execute SELECT on table PILOT.
EXECUTE AS USER = 'USER1'

SELECT * 
FROM PILOT
GO

REVERT

--Q04.2 - Can proceed. User1 has access to execute SELECT on table PILOT.
USE [AIR_CANADA]
GO

GRANT SELECT
	ON [dbo].[PILOT]
	TO [USER1]
GO

--Q04.3
EXECUTE AS USER = 'USER1'

SELECT * 
FROM PILOT
GO

REVERT

--Q04.4
USE [AIR_CANADA]
GO

REVOKE SELECT 
	ON [dbo].[PILOT] 
	TO [USER1]
GO


--Step 05 - INSERT privileges
--Q05.1 - Cannot proceed. User2 doesn't have the privileges to insert in table PILOT.
EXECUTE AS USER = 'USER2'

INSERT INTO PILOT
VALUES (1, 'n1', 123456789, 'Montreal', 40000);
GO

REVERT

--Q05.2
USE [AIR_CANADA]
GO

GRANT INSERT
	ON [dbo].[PILOT]
	TO [USER2]
GO

--Q05.3
EXECUTE AS USER = 'USER2'

INSERT INTO PILOT
VALUES (1, 'n1', 123456789, 'Montreal', 40000);
GO

REVERT

--Q05.4
USE [AIR_CANADA]
GO

REVOKE SELECT 
	ON [dbo].[PILOT] 
	TO [USER2]
GO


--Step 06 - UPDATE privileges
--Q06.1 - Cannot proceed. User3 doesn't have the update privileges on table PILOT.
EXECUTE AS USER = 'USER3'

UPDATE PILOT
set SALARY = 40000
GO

REVERT

--Q06.2
USE [AIR_CANADA]
GO

GRANT UPDATE
	ON [dbo].[PILOT]
	TO [USER3]
GO

--Q06.3 - Can proceed. User has now privileges to update.
EXECUTE AS USER = 'USER3'

UPDATE PILOT
SET SALARY = 40000
GO

REVERT

--Q06.4 *False - The SELECT permission was denied on the object 'PILOT', 
        --database 'AIR_CANADA', schema 'dbo'.*
EXECUTE AS USER = 'USER3'

UPDATE PILOT
SET SALARY = 40000
WHERE NO_PILOT = 4
GO

REVERT


--Q07 *PRIVILÈGE DELETE*
--Q07.1 *FALSE - The SELECT permission was denied on the object 'PILOT', 
        --database 'AIR_CANADA', schema 'dbo'.*
		--*FAUX. The DELETE permission was denied on the object 'PILOT',
		--database 'AIR_CANADA', schema 'dbo'.
EXECUTE AS USER = 'USER4'

DELETE PILOT
WHERE NO_PILOT = 4
GO

REVERT

--Q07.2
USE [AIR_CANADA]
GO

GRANT DELETE
	ON [dbo].[PILOT]
	TO [USER4]
GRANT SELECT
	ON [dbo].[PILOT]
	TO [USER4]
GO

--Q07.3 *FALSE - The SELECT permission was denied on the object 'PILOTE', 
        --database 'AIR_CANADA', schema 'dbo'.*
EXECUTE AS USER = 'USER4'

DELETE PILOT
WHERE NO_PILOT = 4
GO

REVERT

--Q07.4
USE [AIR_CANADA]
GO

DENY DELETE 
	ON [dbo].[PILOT] 
	TO [USER4]
GO


--Step 08 - UPDATE privileges on column.
--Q08.1
USE [AIR_CANADA]
GO

GRANT UPDATE (SALARY, CITY)
	ON [dbo].[PILOT]
	TO [USER5]
GO

--Q08.2
EXECUTE AS USER = 'USER5'

UPDATE PILOT
SET SALARY = 90000, CITY = 'Laval'
GO

REVERT

--Q08.3
EXECUTE AS USER = 'USER5'

UPDATE PILOT
SET SALARY = 90000, CITY = 'Laval'
WHERE NO_PILOT = 5
GO

REVERT


--Step 09 - SELECT privileges on columns.
--Q09.1 *FALSE. The SELECT permission was denied on the object 'PILOTE', 
        --database 'AIR_CANADA', schema 'dbo'.*
EXECUTE AS USER = 'USER6'

SELECT NAS, CITY
FROM PILOT
GO

REVERT

--Q09.2
USE [AIR_CANADA]
GO

GRANT SELECT (NAS, CITY)
	ON [dbo].[PILOT]
	TO [USER6]
GO

--Q09.3
EXECUTE AS USER = 'USER6'

SELECT NAS, CITY
FROM PILOT
GO

REVERT


--Q10 *WITH GRANT OPTION.*
--Q10.1
USE [AIR_CANADA]
GO

GRANT SELECT
	ON [dbo].[PILOT] 
	TO [USER7]
	WITH GRANT OPTION
GO

--Q10.2 - Cannot proceed. Doesn't have the necessary permissions.
EXECUTE AS USER = 'USER8'

SELECT *
FROM PILOT
GO

REVERT

--Q10.3
EXECUTE AS USER = 'USER7'

GRANT SELECT
	ON [dbo].[PILOT] 
	TO [USER8]
	WITH GRANT OPTION
GO

REVERT

--Q10.4
EXECUTE AS USER = 'USER8'

SELECT *
FROM PILOT
GO

REVERT

--Q10.5
USE [AIR_CANADA]
GO

REVOKE SELECT
	ON [dbo].[PILOT] 
	TO [USER7]
	CASCADE
GO

--Q10.6 - False. The user8 cannot execute SELECT command.
EXECUTE AS USER = 'USER8'

SELECT *
FROM PILOT
GO

REVERT